baseURL = '/'
languageCode = 'en-us'
title = 'Triad Machines'
theme = 'half-fast'
relativeURLS = true
disableKinds = "sitemap"
paginate = 9

[menu]

  [[menu.main]]
  name = 'For Wood'
  identifier = 'wood'
  URL = '/for-wood-timber-builders/'
  weight = 1

  [[menu.main]]
  name = 'Wall Panelization for Wood Studs'
  identifier = 'wall_panelization_for_wood_studs'
  parent = 'wood'
  URL = '/wall-panelization-for-wood-studs/'
  weight = 10

  [[menu.main]]
  name = 'Sheathing Bridges'
  identifier = 'sheathing_bridges'
  parent = 'wood'
  URL = '/bridges-for-sheathing-wood-wall-panels/'
  weight = 11

  [[menu.main]]
  name = 'Component Machines'
  identifier = 'component_machines'
  parent = 'wood'
  URL = '/component-machines-for-wood-timber-builders/'
  weight = 12

  [[menu.main]]
  name = 'Floor Cassettes & Decking'
  identifier = 'floor-cassettes-and-decking'
  parent = 'wood'
  URL = '/floor-cassettes-and-decking/'
  weight = 13

  [[menu.main]]
  name = 'Intelligent Material Handling & Staging'
  identifier = 'intelligent-material-handling-and-staging'
  parent = 'wood'
  URL = '/intelligent-material-handling-and-staging/'
  weight = 14

  [[menu.main]]
  name = 'For Steel'
  identifier = 'steel'
  URL = '/for-steel-stud-builders/'
  weight = 2

  [[menu.main]]
  name = 'Wall Panelization for Steel Studs'
  identifier = 'wall_panelization_for_steel_studs'
  parent = 'steel'
  URL = '/wall-panelization-for-steel-studs/'
  weight = 20

  [[menu.main]]
  name = 'Sheathing Bridges'
  identifier = 'sheathing_bridges_for_steel'
  parent = 'steel'
  URL = '/bridges-for-sheathing-steel-stud-wall-panels/'
  weight = 21

  [[menu.main]]
  name = 'Component Machines'
  identifier = 'component_machines_for_steel'
  parent = 'steel'
  URL = '/component-machines-for-steel-stud-builders/'
  weight = 22

  [[menu.main]]
  name = 'Floor Cassettes & Decking'
  identifier = 'floor-cassettes-and-decking'
  parent = 'steel'
  URL = '/floor-cassettes-and-decking/'
  weight = 23

  [[menu.main]]
  name = 'Intelligent Material Handling & Staging'
  identifier = 'intelligent-material-handling-and-staging'
  parent = 'steel'
  URL = '/intelligent-material-handling-and-staging/'
  weight = 24
  
  [[menu.main]]
  name = 'Modular'
  identifier = 'modular'
  URL = '/for-modular-builders/'
  weight = 3
  
  [[menu.main]]
  name = 'For Stairs'
  identifier = 'stairs'
  URL = '/for-professional-stair-builders/'
  weight = 4
  
  [[menu.main]]
  name = 'StairBoss Pro'
  identifier = 'stairboss_pro'
  parent = 'stairs'
  URL = '/machine/stairboss_pro/'
  weight = 40
  
  [[menu.main]]
  name = 'Open Stringer Saw'
  identifier = 'open_stringer_saw'
  parent = 'stairs'
  URL = '/machine/open_stringer_saw/'
  weight = 41
  
  [[menu.main]]
  name = 'Template Stair Router'
  identifier = 'template_stair_router'
  parent = 'stairs'
  URL = '/machine/template_stair_router/'
  weight = 42

  [[menu.main]]
  name = 'Wedge and Glue Block Cutter'
  identifier = 'wedge_and_glue_block_cutter'
  parent = 'stairs'
  URL = '/machine/wedge_and_glue_block_cutter/'
  weight = 43

  [[menu.main]]
  name = 'Staircase Assembly Clamp'
  identifier = 'staircase_assembly_clamp'
  parent = 'stairs'
  URL = '/machine/staircase_assembly_clamp/'
  weight = 44
  
  [[menu.main]]
  name = 'Handrail Boring Machine'
  identifier = 'handrail_machine'
  parent = 'stairs'
  URL = '/machine/balluster-handrail_boring_machine/'
  weight = 45

  [[menu.main]]
  name = 'Bullnose Saw'
  identifier = 'bullnose_saw'
  parent = 'stairs'
  URL = '/machine/bullnose_saw/'
  weight = 46

  [[menu.main]]
  name = 'XSL Overhead Stair Lift'
  identifier = 'xsl_stair_lift'
  parent = 'stairs'
  URL = '/machine/xsl_stair_lift/'
  weight = 47

  [[menu.main]]
  name = 'Heavy Duty Stringer Cart'
  identifier = 'heavy_duty_stringer_cart'
  parent = 'stairs'
  URL = '/machine/heavy_duty_stringer_cart/'
  weight = 48

  [[menu.main]]
  name = 'Specialty'
  identifier = 'specialty'
  URL = '/specialty/'
  weight = 5

  [[menu.main]]
  name = 'Drawer Machine'
  identifier = 'drawer_machine'
  parent = 'specialty'
  URL = '/machine/drawer_machine/'
  weight = 50
  
  [[menu.main]]
  name = 'Pallet Table'
  identifier = 'pallet_table'
  parent = 'specialty'
  URL = '/machine/pallet_table/'
  weight = 51

  [[menu.main]]
  name = 'Contact Us'
  URL = './#contact-us'
  weight = 6

############################## taxonomies ###############################
[taxonomies]
  category = 'categories'
  tag = 'tags'

############################## params ###############################
[params]
  jumbotronimg = '/img/4categories.jpg'

############################## seo ###############################
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

  
