baseURL = '/'
languageCode = 'en-us'
title = 'Triad Machines'
theme = 'hugo-tm'
relativeURLS = true

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = 'For Wood'
  identifier = 'wood'
  URL = 'for-timber-stick-builders'
  weight = 1

  [[menu.main]]
  name = 'Framing Tables'
  identifier = 'framing_tables'
  parent = 'wood'
  URL = 'framing_tables'
  weight = 10

  [[menu.main]]
  name = 'Sheathing and Squaring Tables'
  identifier = 'sheathing_and_squaring_tables'
  parent = 'wood'
  URL = 'sheathing_tables'
  weight = 11

  [[menu.main]]
  name = 'Sheathing Bridges'
  identifier = 'sheathing_bridges'
  parent = 'wood'
  URL = 'sheathing_bridges'
  weight = 12

  [[menu.main]]
  name = 'Component Machines'
  identifier = 'component_machines'
  parent = 'wood'
  URL = 'component_machines'
  weight = 13

  [[menu.main]]
  name = 'For Steel'
  identifier = 'steel'
  URL = 'for-steel-stud-builders'
  weight = 2

  [[menu.main]]
  name = 'Framing Tables'
  identifier = 'framing_tables_for_steel_studs'
  parent = 'steel'
  URL = 'framing_tables_for_steel_studs'
  weight = 20

  [[menu.main]]
  name = 'Sheathing and Squaring Tables'
  identifier = 'sheathing_and_squaring_tables_for_steel'
  parent = 'steel'
  URL = 'sheathing_and_squaring_tables_for_steel'
  weight = 21

  [[menu.main]]
  name = 'Sheathing Bridges'
  identifier = 'sheathing_bridges_for_steel'
  parent = 'steel'
  URL = 'sheathing_bridges'
  weight = 22

  [[menu.main]]
  name = 'Component Machines'
  identifier = 'component_machines_for_steel'
  parent = 'steel'
  URL = 'component_machines_for_steel'
  weight = 23
  
  [[menu.main]]
  name = 'Modular'
  identifier = 'modular'
  URL = 'for-modular-builders'
  weight = 3
  
  [[menu.main]]
  name = 'For Stairs'
  identifier = 'stairs'
  URL = 'for-stair-builders'
  weight = 4
  
  [[menu.main]]
  name = 'StairBoss Pro'
  identifier = 'stairboss_pro'
  parent = 'stairs'
  URL = 'machine/StairBoss_Pro'
  weight = 40
  
  [[menu.main]]
  name = 'Open Stringer Saw'
  identifier = 'open_stringer_saw'
  parent = 'stairs'
  URL = 'machine/Open_Stringer_Saw/'
  weight = 41

    
  [[menu.main]]
  name = 'Template Stair Router'
  identifier = 'template_stair_router'
  parent = 'stairs'
  URL = 'machine/Template_Stair_Router'
  weight = 42

  [[menu.main]]
  name = 'Wedge and Glue Block Cutter'
  identifier = 'wedge_and_glue_block_cutter'
  parent = 'stairs'
  URL = 'machine/Wedge_and_Glue_Block_Cutter'
  weight = 43

  [[menu.main]]
  name = 'Staircase Assembly Clamp'
  identifier = 'staircase_assembly_clamp'
  parent = 'stairs'
  URL = 'machine/Staircase_Assembly_Clamp'
  weight = 44
  
  [[menu.main]]
  name = 'Handrail Boring Machine'
  identifier = 'handrail_machine'
  parent = 'stairs'
  URL = 'machine/Balluster-Handrail_Boring_Machine'
  weight = 45

  [[menu.main]]
  name = 'Bullnose Saw'
  identifier = 'bullnose_saw'
  parent = 'stairs'
  URL = 'Bullnose_Saw'
  weight = 46


  [[menu.main]]
  name = 'XSL Overhead Stair Lift'
  identifier = 'xsl_stair_lift'
  parent = 'stairs'
  URL = 'XSL_Overhead_Stair_Lift'
  weight = 47

  [[menu.main]]
  name = 'Heavy Duty Stringer Cart'
  identifier = 'heavy_duty_stringer_cart'
  parent = 'stairs'
  URL = 'Heavy_Duty_Stringer_Cart'
  weight = 48

  [[menu.main]]
  name = 'Specialty'
  identifier = 'specialty'
  URL = 'specialty'
  weight = 5

  [[menu.main]]
  name = 'Drawer Machine'
  identifier = 'drawer_machine'
  parent = 'specialty'
  URL = 'machine/drawer_machine'
  
  [[menu.main]]
  name = 'Pallet Machine'
  identifier = 'pallet_table'
  parent = 'specialty'
  URL = 'machine/pallet_table'

  [[menu.main]]
  name = 'Contact Us'
  URL = './#contact-us'
  weight = 6

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  jumbotronimg = '/img/4categories.jpg'